#!/usr/bin/env python3
"""check_docs — doc linter and index generator for bootstrap-kit projects.

Usage: check_docs.py [--fix] [--root PATH] [--stale-hours N]
Exit status 1 if any E-code finding, else 0. Warnings (W-codes) print but pass.
"""
from __future__ import annotations

import argparse
import re
import sys
import tomllib
from dataclasses import dataclass, field
from datetime import datetime, timedelta, timezone
from pathlib import Path

GENERATED_MARKER = "<!-- generated by tools/check_docs.py --fix; do not edit by hand -->"
DEFAULT_EXCLUDE = (".git", "node_modules", ".venv", "__pycache__")
PLACEHOLDER_SCOPE_ROOT_FILES = ("AGENTS.md", "CLAUDE.md", "DOCS.md", "README.md")
ACTIVE_MILESTONE_STATUSES = ("planned", "in progress", "done")


# --------------------------------------------------------------------------- data


@dataclass
class Finding:
    code: str
    path: str
    line: int
    message: str

    @property
    def is_error(self) -> bool:
        return self.code.startswith("E")

    def __str__(self) -> str:
        return f"{self.path}:{self.line}: {self.code} {self.message}"


@dataclass
class Config:
    root: Path
    codename_placeholder: str | None = None
    stale_hours: float = 24
    allow_tbd_in: list[str] = field(default_factory=lambda: ["docs/OPEN-QUESTIONS.md"])
    citation_exclude: list[str] = field(default_factory=list)
    exclude: list[str] = field(default_factory=lambda: list(DEFAULT_EXCLUDE))
    tier: str = "auto"

    @property
    def docs(self) -> Path:
        return self.root / "docs"


def load_config(root: Path) -> Config:
    cfg = Config(root=Path(root))
    path = cfg.docs / ".check_docs.toml"
    if path.exists():
        data = tomllib.loads(path.read_text(encoding="utf-8"))
        for key in ("codename_placeholder", "stale_hours", "allow_tbd_in", "citation_exclude", "tier"):
            if key in data:
                setattr(cfg, key, data[key])
        if "exclude" in data:
            cfg.exclude = list(DEFAULT_EXCLUDE) + list(data["exclude"])
    return cfg


# --------------------------------------------------------------------------- run / main


def run(root: Path, fix: bool = False, stale_hours: float | None = None) -> list[Finding]:
    cfg = load_config(Path(root))
    if stale_hours is not None:
        cfg.stale_hours = stale_hours
    return []


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Doc linter and index generator.")
    ap.add_argument("--root", default=".", help="project root (default: current directory)")
    ap.add_argument("--fix", action="store_true", help="regenerate index files and CURRENT.md")
    ap.add_argument("--stale-hours", type=float, default=None, help="claim staleness threshold")
    args = ap.parse_args(argv)
    findings = run(Path(args.root).resolve(), fix=args.fix, stale_hours=args.stale_hours)
    for f in sorted(findings, key=lambda f: (f.path, f.line, f.code)):
        print(f)
    n_err = sum(1 for f in findings if f.is_error)
    n_warn = len(findings) - n_err
    print(f"{n_err} error(s), {n_warn} warning(s)")
    return 1 if n_err else 0


if __name__ == "__main__":
    sys.exit(main())
