#!/usr/bin/env python3
"""check_docs — doc linter and index generator for bootstrap-kit projects.

Usage: check_docs.py [--fix] [--root PATH] [--stale-hours N]
Exit status 1 if any E-code finding, else 0. Warnings (W-codes) print but pass.
"""
from __future__ import annotations

import argparse
import re
import sys
import tomllib
from dataclasses import dataclass, field
from datetime import datetime, timedelta, timezone
from pathlib import Path

GENERATED_MARKER = "<!-- generated by tools/check_docs.py --fix; do not edit by hand -->"
DEFAULT_EXCLUDE = (".git", "node_modules", ".venv", "__pycache__")
PLACEHOLDER_SCOPE_ROOT_FILES = ("AGENTS.md", "CLAUDE.md", "DOCS.md", "README.md")
ACTIVE_MILESTONE_STATUSES = ("planned", "in progress", "done")


# --------------------------------------------------------------------------- data


@dataclass
class Finding:
    code: str
    path: str
    line: int
    message: str

    @property
    def is_error(self) -> bool:
        return self.code.startswith("E")

    def __str__(self) -> str:
        return f"{self.path}:{self.line}: {self.code} {self.message}"


@dataclass
class Config:
    root: Path
    codename_placeholder: str | None = None
    stale_hours: float = 24
    allow_tbd_in: list[str] = field(default_factory=lambda: ["docs/OPEN-QUESTIONS.md"])
    citation_exclude: list[str] = field(default_factory=list)
    exclude: list[str] = field(default_factory=lambda: list(DEFAULT_EXCLUDE))
    tier: str = "auto"

    @property
    def docs(self) -> Path:
        return self.root / "docs"


def load_config(root: Path) -> Config:
    cfg = Config(root=Path(root))
    path = cfg.docs / ".check_docs.toml"
    if path.exists():
        data = tomllib.loads(path.read_text(encoding="utf-8"))
        for key in ("codename_placeholder", "stale_hours", "allow_tbd_in", "citation_exclude", "tier"):
            if key in data:
                setattr(cfg, key, data[key])
        if "exclude" in data:
            cfg.exclude = list(DEFAULT_EXCLUDE) + list(data["exclude"])
    return cfg


# --------------------------------------------------------------------------- markdown helpers

HEADING_RE = re.compile(r"^(#{1,6})[ \t]+(.*?)[ \t]*$", re.M)
NUMBERED_RE = re.compile(r"^(\d+(?:\.\d+)*[a-z]?)\.?(?=\s)")
# A citation is `path/to/file.md` optionally followed by `§N.M`. The lookbehind rejects
# tokens glued to template braces, angle brackets, a hyphen, a slash, a dot or a colon,
# so `{{x}}-design.md`, `M<n>.md`, `<file>.md` and `https://example.com/x.md` never match.
CITE_RE = re.compile(
    r"(?<![\w{}<>\-/.:])((?:[\w.-]+/)*[A-Za-z0-9_][\w.-]*\.md)(?:[ \t]*§[ \t]*(\d+(?:\.\d+)*[a-z]?))?"
)


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8").replace("\r\n", "\n")


def rel(cfg: Config, path: Path) -> str:
    return path.resolve().relative_to(cfg.root.resolve()).as_posix()


def _excluded(cfg: Config, relpath: str) -> bool:
    parts = relpath.split("/")
    for e in cfg.exclude:
        e = e.strip("/")
        if "/" in e:
            if relpath == e or relpath.startswith(e + "/"):
                return True
        elif e in parts:
            return True
    return False


def iter_md(cfg: Config) -> list[Path]:
    return [p for p in sorted(cfg.root.rglob("*.md")) if not _excluded(cfg, rel(cfg, p))]


def line_of(text: str, pos: int) -> int:
    return text.count("\n", 0, pos) + 1


def numbered_headings(text: str) -> set[str]:
    out: set[str] = set()
    for m in HEADING_RE.finditer(text):
        n = NUMBERED_RE.match(m.group(2) + " ")
        if n:
            out.add(n.group(1))
    return out


def first_heading(text: str) -> str:
    m = HEADING_RE.search(text)
    return m.group(2).strip() if m else ""


def field_value(text: str, name: str) -> str | None:
    """Value of a `**Name:** value` line, or None if absent. Empty and dash values become ''."""
    m = re.search(rf"^\*\*{re.escape(name)}:\*\*[ \t]*(.*?)[ \t]*$", text, re.M)
    if not m:
        return None
    v = m.group(1).strip()
    return "" if v in ("", "—", "-", "n/a") else v


def section_body(text: str, title: str) -> str:
    """Body of the `## title` section, up to the next `## ` heading."""
    m = re.search(rf"^## {re.escape(title)}[ \t]*$\n?(.*?)(?=^## |\Z)", text, re.M | re.S)
    return m.group(1) if m else ""


# --------------------------------------------------------------------------- checks: citations


def _resolve_citation(cfg: Config, citing: Path, target: str) -> Path | None:
    for base in (citing.parent, cfg.root, cfg.docs):
        cand = base / target
        if cand.is_file():
            return cand
    return None


def check_citations(cfg: Config, md_files: list[Path]) -> list[Finding]:
    out: list[Finding] = []
    heading_cache: dict[Path, set[str]] = {}
    for path in md_files:
        r = rel(cfg, path)
        if any(r == x.strip("/") or r.startswith(x.strip("/") + "/") for x in cfg.citation_exclude):
            continue
        text = read_text(path)
        for m in CITE_RE.finditer(text):
            target, anchor = m.group(1), m.group(2)
            resolved = _resolve_citation(cfg, path, target)
            if resolved is None:
                out.append(Finding("E001", r, line_of(text, m.start()), f"cited file missing: {target}"))
                continue
            if anchor:
                if resolved not in heading_cache:
                    heading_cache[resolved] = numbered_headings(read_text(resolved))
                if anchor not in heading_cache[resolved]:
                    out.append(Finding("E002", r, line_of(text, m.start()),
                                       f"no heading §{anchor} in {target}"))
    return out


# --------------------------------------------------------------------------- run / main


def run(root: Path, fix: bool = False, stale_hours: float | None = None) -> list[Finding]:
    cfg = load_config(Path(root))
    if stale_hours is not None:
        cfg.stale_hours = stale_hours
    md_files = iter_md(cfg)
    findings: list[Finding] = []
    findings += check_citations(cfg, md_files)
    return findings


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Doc linter and index generator.")
    ap.add_argument("--root", default=".", help="project root (default: current directory)")
    ap.add_argument("--fix", action="store_true", help="regenerate index files and CURRENT.md")
    ap.add_argument("--stale-hours", type=float, default=None, help="claim staleness threshold")
    args = ap.parse_args(argv)
    findings = run(Path(args.root).resolve(), fix=args.fix, stale_hours=args.stale_hours)
    for f in sorted(findings, key=lambda f: (f.path, f.line, f.code)):
        print(f)
    n_err = sum(1 for f in findings if f.is_error)
    n_warn = len(findings) - n_err
    print(f"{n_err} error(s), {n_warn} warning(s)")
    return 1 if n_err else 0


if __name__ == "__main__":
    sys.exit(main())
