#!/usr/bin/env python3
"""check_docs — doc linter and index generator for bootstrap-kit projects.

Usage: check_docs.py [--fix] [--root PATH] [--stale-hours N]
Exit status 1 if any E-code finding, else 0. Warnings (W-codes) print but pass.
"""
from __future__ import annotations

import argparse
import re
import sys
import tomllib
from dataclasses import dataclass, field
from datetime import datetime, timedelta, timezone
from pathlib import Path

GENERATED_MARKER = "<!-- generated by tools/check_docs.py --fix; do not edit by hand -->"
DEFAULT_EXCLUDE = (".git", "node_modules", ".venv", "__pycache__")
PLACEHOLDER_SCOPE_ROOT_FILES = ("AGENTS.md", "CLAUDE.md", "DOCS.md", "README.md")
ACTIVE_MILESTONE_STATUSES = ("planned", "in progress", "done")


# --------------------------------------------------------------------------- data


@dataclass
class Finding:
    code: str
    path: str
    line: int
    message: str

    @property
    def is_error(self) -> bool:
        return self.code.startswith("E")

    def __str__(self) -> str:
        return f"{self.path}:{self.line}: {self.code} {self.message}"


@dataclass
class Config:
    root: Path
    codename_placeholder: str | None = None
    stale_hours: float = 24
    allow_tbd_in: list[str] = field(default_factory=lambda: ["docs/OPEN-QUESTIONS.md"])
    citation_exclude: list[str] = field(default_factory=list)
    exclude: list[str] = field(default_factory=lambda: list(DEFAULT_EXCLUDE))
    tier: str = "auto"

    @property
    def docs(self) -> Path:
        return self.root / "docs"


def load_config(root: Path) -> Config:
    cfg = Config(root=Path(root))
    path = cfg.docs / ".check_docs.toml"
    if path.exists():
        data = tomllib.loads(path.read_text(encoding="utf-8"))
        for key in ("codename_placeholder", "stale_hours", "allow_tbd_in", "citation_exclude", "tier"):
            if key in data:
                setattr(cfg, key, data[key])
        if "exclude" in data:
            cfg.exclude = list(DEFAULT_EXCLUDE) + list(data["exclude"])
    return cfg


# --------------------------------------------------------------------------- markdown helpers

HEADING_RE = re.compile(r"^(#{1,6})[ \t]+(.*?)[ \t]*$", re.M)
NUMBERED_RE = re.compile(r"^(\d+(?:\.\d+)*[a-z]?)\.?(?=\s)")
# A citation is `path/to/file.md` optionally followed by `§N.M`. The lookbehind rejects
# tokens glued to template braces, angle brackets, a hyphen, a slash, a dot or a colon,
# so `{{x}}-design.md`, `M<n>.md`, `<file>.md` and `https://example.com/x.md` never match.
CITE_RE = re.compile(
    r"(?<![\w{}<>\-/.:])((?:[\w.-]+/)*[A-Za-z0-9_][\w.-]*\.md)(?:[ \t]*§[ \t]*(\d+(?:\.\d+)*[a-z]?))?"
)


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8").replace("\r\n", "\n")


def rel(cfg: Config, path: Path) -> str:
    return path.resolve().relative_to(cfg.root.resolve()).as_posix()


def _excluded(cfg: Config, relpath: str) -> bool:
    parts = relpath.split("/")
    for e in cfg.exclude:
        e = e.strip("/")
        if "/" in e:
            if relpath == e or relpath.startswith(e + "/"):
                return True
        elif e in parts:
            return True
    return False


def iter_md(cfg: Config) -> list[Path]:
    return [p for p in sorted(cfg.root.rglob("*.md")) if not _excluded(cfg, rel(cfg, p))]


def line_of(text: str, pos: int) -> int:
    return text.count("\n", 0, pos) + 1


def numbered_headings(text: str) -> set[str]:
    out: set[str] = set()
    for m in HEADING_RE.finditer(text):
        n = NUMBERED_RE.match(m.group(2) + " ")
        if n:
            out.add(n.group(1))
    return out


def first_heading(text: str) -> str:
    m = HEADING_RE.search(text)
    return m.group(2).strip() if m else ""


def field_value(text: str, name: str) -> str | None:
    """Value of a `**Name:** value` line, or None if absent. Empty and dash values become ''."""
    m = re.search(rf"^\*\*{re.escape(name)}:\*\*[ \t]*(.*?)[ \t]*$", text, re.M)
    if not m:
        return None
    v = m.group(1).strip()
    return "" if v in ("", "—", "-", "n/a") else v


def section_body(text: str, title: str) -> str:
    """Body of the `## title` section, up to the next `## ` heading."""
    m = re.search(rf"^## {re.escape(title)}[ \t]*$\n?(.*?)(?=^## |\Z)", text, re.M | re.S)
    return m.group(1) if m else ""


# --------------------------------------------------------------------------- model


@dataclass
class Feature:
    id: str
    title: str
    ticked: bool
    moved_to: str | None
    plan_path: str | None
    depends_on: list[str]
    line: int


@dataclass
class Milestone:
    id: str
    path: Path
    title: str
    status: str
    exit_criteria: str
    evidence: str
    depends_on: list[str]
    features: list[Feature]

    def feature(self, fid: str) -> Feature | None:
        return next((f for f in self.features if f.id == fid), None)


@dataclass
class Plan:
    id: str
    path: Path
    title: str
    status: str
    moved_to: str | None
    milestone: str
    depends_on: list[str]
    stamps: list[tuple[datetime, str]]
    last_note: str
    tasks_open: int


@dataclass
class Adr:
    number: str
    path: Path
    title: str
    status: str


@dataclass
class Phase:
    id: str
    title: str
    status: str
    line: int
    milestones: list[str] = field(default_factory=list)


@dataclass
class Roadmap:
    path: Path
    phases: list[Phase]
    milestone_titles: dict[str, str]
    sketch_ranges: list[tuple[int, int]]
    order: list[str]


@dataclass
class Project:
    cfg: Config
    tier: str
    md_files: list[Path]
    milestones: dict[str, Milestone]
    plans: dict[str, Plan]
    adrs: list[Adr]
    roadmap: Roadmap | None

    def status_of(self, mid: str) -> str | None:
        if mid in self.milestones:
            return self.milestones[mid].status
        if self.roadmap and mid in self.roadmap.milestone_titles:
            return "sketch"
        return None

    def feature_of(self, fid: str) -> tuple[Milestone, Feature] | None:
        for m in self.milestones.values():
            f = m.feature(fid)
            if f:
                return m, f
        return None

    def milestone_order(self) -> list[str]:
        ordered = list(self.roadmap.order) if self.roadmap else []
        for mid in sorted(self.milestones, key=lambda s: int(s[1:])):
            if mid not in ordered:
                ordered.append(mid)
        return ordered


# --------------------------------------------------------------------------- parsers

ID_LIST_RE = re.compile(r"\bM\d+(?:-\d+)?\b")
FEATURE_RE = re.compile(
    r"^- \[([ xX])\] (M\d+-\d+) — (.*?)(?: — `([^`]+)`)?(?: \(depends on: ([^)]*)\))?[ \t]*$", re.M
)
MOVED_FEATURE_RE = re.compile(r"^- ~~(M\d+-\d+) — (.*?)~~ moved to (M\d+-\d+)[ \t]*$", re.M)
SESSION_RE = re.compile(r"^- (\S+)(?: — ([^—\n]*?))?(?: — ([^\n]*))?[ \t]*$", re.M)
TASK_RE = re.compile(r"^- \[([ xX])\] T\d+", re.M)
ADR_FILE_RE = re.compile(r"^(\d{4})-.+\.md$")


def parse_ids(value: str | None) -> list[str]:
    return ID_LIST_RE.findall(value or "")


def _id_and_title(heading: str, pattern: str, fallback_id: str) -> tuple[str, str]:
    m = re.match(rf"({pattern})\s+—\s+(.*)$", heading)
    if m:
        return m.group(1), m.group(2).strip()
    return fallback_id, heading


def parse_milestone(path: Path) -> Milestone:
    text = read_text(path)
    mid, title = _id_and_title(first_heading(text), r"M\d+", path.stem)
    features: list[Feature] = []
    for m in FEATURE_RE.finditer(text):
        features.append(Feature(m.group(2), m.group(3).strip(), m.group(1) in "xX", None,
                                m.group(4), parse_ids(m.group(5)), line_of(text, m.start())))
    for m in MOVED_FEATURE_RE.finditer(text):
        features.append(Feature(m.group(1), m.group(2).strip(), False, m.group(3), None, [],
                                line_of(text, m.start())))
    features.sort(key=lambda f: f.line)
    return Milestone(
        id=mid, path=path, title=title,
        status=(field_value(text, "Status") or "").lower(),
        exit_criteria=field_value(text, "Exit criteria") or "",
        evidence=field_value(text, "Evidence of exit") or "",
        depends_on=parse_ids(field_value(text, "Depends on")),
        features=features,
    )


def parse_stamp(s: str) -> datetime | None:
    s = s.strip()
    if s.endswith("Z"):
        s = s[:-1] + "+00:00"
    try:
        dt = datetime.fromisoformat(s)
    except ValueError:
        return None
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)
    return dt


def parse_plan(path: Path) -> Plan:
    text = read_text(path)
    fallback = re.match(r"(M\d+-\d+)", path.stem)
    pid, title = _id_and_title(first_heading(text), r"M\d+-\d+", fallback.group(1) if fallback else path.stem)
    status_field = field_value(text, "Status") or ""
    status_raw = status_field.lower()
    moved_to = None
    status = status_raw
    if status_raw.startswith("moved"):
        status = "moved"
        ids = parse_ids(status_field) or parse_ids(field_value(text, "Moved to"))
        moved_to = ids[0] if ids else None
    stamps: list[tuple[datetime, str]] = []
    for m in SESSION_RE.finditer(section_body(text, "Sessions")):
        dt = parse_stamp(m.group(1))
        if dt:
            stamps.append((dt, (m.group(2) or "").strip()))
    notes = [ln[2:].strip() for ln in section_body(text, "Progress notes").splitlines() if ln.startswith("- ")]
    tasks_open = sum(1 for m in TASK_RE.finditer(section_body(text, "Tasks")) if m.group(1) == " ")
    milestone = field_value(text, "Milestone") or pid.split("-")[0]
    return Plan(pid, path, title, status, moved_to, milestone, parse_ids(field_value(text, "Depends on")),
                stamps, notes[-1] if notes else "", tasks_open)


def parse_adr(path: Path) -> Adr:
    text = read_text(path)
    number = ADR_FILE_RE.match(path.name).group(1)
    title = re.sub(r"^\d{4}\.\s*", "", first_heading(text)) or path.stem
    return Adr(number, path, title, (field_value(text, "Status") or "").lower())


def parse_roadmap(path: Path) -> Roadmap:
    text = read_text(path)
    lines = text.split("\n")
    heads = [(line_of(text, m.start()), len(m.group(1)), m.group(2).strip()) for m in HEADING_RE.finditer(text)]

    def section_end(idx: int) -> int:
        """Last line of the section including nested sub-headings."""
        level = heads[idx][1]
        for j in range(idx + 1, len(heads)):
            if heads[j][1] <= level:
                return heads[j][0] - 1
        return len(lines)

    def own_end(idx: int) -> int:
        """Last line before the next heading of any level: the section's own body only."""
        return heads[idx + 1][0] - 1 if idx + 1 < len(heads) else len(lines)

    def status_in(start: int, end: int) -> str:
        return (field_value("\n".join(lines[start - 1:end]), "Status") or "").lower()

    phases: list[Phase] = []
    titles: dict[str, str] = {}
    sketch: list[tuple[int, int]] = []
    order: list[str] = []
    current: Phase | None = None
    for i, (ln, level, title) in enumerate(heads):
        pm = re.match(r"(P\d+)\s+—\s+(.*)$", title)
        mm = re.match(r"(M\d+)\s+—\s+(.*)$", title)
        end = section_end(i)
        if pm:
            current = Phase(pm.group(1), pm.group(2), status_in(ln, own_end(i)), ln)
            phases.append(current)
            if current.status == "sketch":
                sketch.append((ln, end))
        elif mm:
            titles[mm.group(1)] = mm.group(2)
            order.append(mm.group(1))
            if current is not None and level > 2:
                current.milestones.append(mm.group(1))
            if status_in(ln, own_end(i)) == "sketch":
                sketch.append((ln, end))
        else:
            current = None if level <= 2 else current
    return Roadmap(path, phases, titles, sketch, order)


# --------------------------------------------------------------------------- loader


def detect_tier(cfg: Config) -> str:
    if cfg.tier != "auto":
        return cfg.tier
    if (cfg.docs / "milestones").is_dir():
        return "standard"
    if (cfg.docs / "roadmap.md").is_file():
        return "lite"
    return "minimal"


def load_project(cfg: Config) -> Project:
    tier = detect_tier(cfg)
    milestones: dict[str, Milestone] = {}
    plans: dict[str, Plan] = {}
    adrs: list[Adr] = []
    roadmap: Roadmap | None = None
    if tier == "standard":
        for p in sorted((cfg.docs / "milestones").glob("M*.md")):
            m = parse_milestone(p)
            milestones[m.id] = m
        for p in sorted((cfg.docs / "plans").rglob("M*-*.md")):
            pl = parse_plan(p)
            plans[pl.id] = pl
    if tier in ("standard", "lite") and (cfg.docs / "roadmap.md").is_file():
        roadmap = parse_roadmap(cfg.docs / "roadmap.md")
    dec = cfg.docs / "decisions"
    if dec.is_dir():
        adrs = [parse_adr(p) for p in sorted(dec.glob("*.md")) if ADR_FILE_RE.match(p.name)]
    return Project(cfg, tier, iter_md(cfg), milestones, plans, adrs, roadmap)


# --------------------------------------------------------------------------- checks: citations


def _resolve_citation(cfg: Config, citing: Path, target: str) -> Path | None:
    for base in (citing.parent, cfg.root, cfg.docs):
        cand = base / target
        if cand.is_file():
            return cand
    return None


def check_citations(cfg: Config, md_files: list[Path]) -> list[Finding]:
    out: list[Finding] = []
    heading_cache: dict[Path, set[str]] = {}
    for path in md_files:
        r = rel(cfg, path)
        if any(r == x.strip("/") or r.startswith(x.strip("/") + "/") for x in cfg.citation_exclude):
            continue
        text = read_text(path)
        for m in CITE_RE.finditer(text):
            target, anchor = m.group(1), m.group(2)
            resolved = _resolve_citation(cfg, path, target)
            if resolved is None:
                out.append(Finding("E001", r, line_of(text, m.start()), f"cited file missing: {target}"))
                continue
            if anchor:
                if resolved not in heading_cache:
                    heading_cache[resolved] = numbered_headings(read_text(resolved))
                if anchor not in heading_cache[resolved]:
                    out.append(Finding("E002", r, line_of(text, m.start()),
                                       f"no heading §{anchor} in {target}"))
    return out


# --------------------------------------------------------------------------- run / main


def run(root: Path, fix: bool = False, stale_hours: float | None = None) -> list[Finding]:
    cfg = load_config(Path(root))
    if stale_hours is not None:
        cfg.stale_hours = stale_hours
    project = load_project(cfg)
    return check(project)


def check(project: Project) -> list[Finding]:
    cfg = project.cfg
    findings: list[Finding] = []
    findings += check_citations(cfg, project.md_files)
    return findings


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Doc linter and index generator.")
    ap.add_argument("--root", default=".", help="project root (default: current directory)")
    ap.add_argument("--fix", action="store_true", help="regenerate index files and CURRENT.md")
    ap.add_argument("--stale-hours", type=float, default=None, help="claim staleness threshold")
    args = ap.parse_args(argv)
    findings = run(Path(args.root).resolve(), fix=args.fix, stale_hours=args.stale_hours)
    for f in sorted(findings, key=lambda f: (f.path, f.line, f.code)):
        print(f)
    n_err = sum(1 for f in findings if f.is_error)
    n_warn = len(findings) - n_err
    print(f"{n_err} error(s), {n_warn} warning(s)")
    return 1 if n_err else 0


if __name__ == "__main__":
    sys.exit(main())
